// Generates the landing page for the Zig autodoc site.
//
// Usage: node scripts/build-index.mjs <site-dir> <projects.json>
//
// Every project listed in projects.json gets a row. Projects whose build leg
// failed have no directory under <site-dir>; those rows are marked instead of
// silently dropped, so a broken library is visible rather than invisible.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const [siteDir, projectsPath] = process.argv.slice(2);
if (!siteDir || !projectsPath) {
  console.error('usage: build-index.mjs <site-dir> <projects.json>');
  process.exit(2);
}

const projects = JSON.parse(readFileSync(projectsPath, 'utf8'));
const zigVersion = '0.16.0';

const escape = (value) =>
  String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');

const rows = projects.map((project) => {
  const published = existsSync(join(siteDir, project.name, 'index.html'));
  const state = published
    ? `<a href="./${escape(project.name)}/">${escape(project.name)}</a>`
    : `<span class="missing">${escape(project.name)}</span>`;
  const repo = `https://github.com/${project.repo}`;
  const fork = project.fork_of ? ` <span class="fork">fork of ${escape(project.fork_of)}</span>` : '';
  return `<li class="${published ? '' : 'unpublished'}">
      <div class="name">${state}${fork}</div>
      <div class="desc">${escape(project.description ?? '')}</div>
      <div class="meta">
        <a href="${escape(repo)}">source</a>
        <span class="commit">${escape(project.ref)}</span>
      </div>
    </li>`;
});

const publishedCount = projects.filter((project) =>
  existsSync(join(siteDir, project.name, 'index.html')),
).length;

const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Zig autodoc</title>
    <meta name="description" content="Autodoc API reference for Zig libraries, published by GitHub Actions." />
    <style>
      :root {
        color-scheme: light dark;
        --fg: #16161d;
        --bg: #fbfbfd;
        --muted: #5b5b66;
        --accent: #2a6286;
        --line: #d9d9e0;
      }
      @media (prefers-color-scheme: dark) {
        :root {
          --fg: #e6e6ea;
          --bg: #16161d;
          --muted: #9a9aa6;
          --accent: #7fb2d9;
          --line: #33333d;
        }
      }
      * { box-sizing: border-box; }
      body {
        margin: 0 auto;
        padding: 3rem 1.25rem 4rem;
        max-width: 52rem;
        font-family: system-ui, -apple-system, 'Segoe UI', sans-serif;
        line-height: 1.5;
        color: var(--fg);
        background: var(--bg);
      }
      h1 { font-size: 1.75rem; margin: 0 0 .35rem; }
      h2 { font-size: 1.05rem; margin: 2.5rem 0 .75rem; font-weight: 600; }
      p.lede { margin: 0 0 1.5rem; color: var(--muted); }
      ul { list-style: none; margin: 0; padding: 0; border-top: 1px solid var(--line); }
      li { padding: .8rem 0; border-bottom: 1px solid var(--line); }
      .name { font-size: 1.05rem; font-weight: 600; }
      .name a { color: var(--accent); text-decoration: none; }
      .name a:hover { text-decoration: underline; }
      .name .missing { color: var(--muted); font-style: italic; font-weight: 500; }
      .fork { color: var(--muted); font-size: .8rem; font-weight: 400; }
      .desc { color: var(--muted); font-size: .95rem; }
      .meta { font-size: .8rem; margin-top: .2rem; }
      .meta a { color: var(--accent); }
      .commit { color: var(--muted); font-family: ui-monospace, monospace; margin-left: .6rem; }
      li.unpublished { opacity: .55; }
      footer { margin-top: 2.5rem; color: var(--muted); font-size: .8rem; }
      code { font-family: ui-monospace, monospace; font-size: .9em; }
    </style>
  </head>
  <body>
    <h1>Zig autodoc</h1>
    <p class="lede">
      API reference for Zig libraries, generated by <code>zig build-obj -femit-docs</code>
      with Zig ${escape(zigVersion)} and published by GitHub Actions.
      ${publishedCount} of ${projects.length} libraries built.
    </p>
    <ul>
${rows.join('\n')}
    </ul>
    <h2>Notes</h2>
    <p class="desc">
      Every library page is a self-contained autodoc bundle: <code>index.html</code>,
      <code>main.js</code>, <code>main.wasm</code>, and <code>sources.tar</code>.
      It must be served over HTTP — <code>file://</code> fails because the page
      fetches and instantiates the wasm. Search and the declaration tree come from
      <code>main.wasm</code>; source views come from <code>sources.tar</code>,
      which is stripped of the <code>std</code> module so that each page ships
      kilobytes instead of a second copy of the standard library. The Zig standard
      library is still searchable in every page.
    </p>
    <footer>
      Rebuilt on every push to this repository's default branch, weekly, and on manual
      dispatch. Add a library by editing <code>projects.json</code>.
    </footer>
  </body>
</html>
`;

writeFileSync(join(siteDir, 'index.html'), html);
console.log(`build-index: ${publishedCount}/${projects.length} libraries published`);